### ISSUE TITLE
Build for FlexibleMink 1.0 broken

### ISSUE THREAD

**Issue by BKorenek** [Medology/FlexibleMink#316]
## Describe the bug
Build appears to be broken for FlexibleMink 1.0. 2.0 is behaving fine. Per donald we previously used our own Composer image, but no longer do. The error appears to not be able to find a composer image. 

https://circleci.com/gh/Medology/FlexibleMink/1899?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jose-ochoa** [comment]
Scored with @johnnie502 and @fortoulrodolfo

**Comment by juliohl** [comment]
### QA - Local

Verified with @jose-ochoa and for this ticket there are no tests we can run since the bug was related to a broken step on the Circle-CI workflow, no app code were touched. Moving it to **Deploy & Test**.

Adding a screenshot of previous broken workflow against fixed one.

![image](https://user-images.githubusercontent.com/61750578/76095637-3e165d00-5f8a-11ea-8321-581ccc5fbf99.png)

**Comment by juliohl** [comment]
As per conversation with @Chekote, FlexibleMink tickets (like this one) will not be "QA'ed" by us given the nature of the tool.
