### ISSUE TITLE
[99] Scrutinizer check not running due to inability to check submodules [private repo]

### ISSUE THREAD

**Issue by jose-ochoa** [Medology/FlexibleMink#359]
# Story
**As a dev of FlexibleMink**, I need to ensure my coding style is written to the expected standard.

## Steps to Recreate  
Open a PR on this repo, the Scrutinizer check runs automatically for every PR.

## Expected Behavior  
Scrutinizer should run its check

## Actual Behavior
Fails to execute check because it does not have the ability to checkout submodules, a requirement before running the check.

## Business Value
Ensure the code base adhere to a style standard, expedites the review of PR and merging, at this time requires dev with the superpower to merge and requires dev to force code review

## Notes
![image](https://user-images.githubusercontent.com/16085034/109991883-579ed180-7cd0-11eb-876e-0922fce9ec62.png)

## Acceptance Criteria
- [X] Expected Behavior is exhibited when steps to recreate are followed

or

- [ ] Bug could not be reproduced but additional logging has been added

## Announcement Message
releasenotes: N/A

devchat: The Scrutinizer check for FlexibleMink has been fixed.

# Proposed Solution  
No Idea

## Subject Matter Experts
- Juan
- Donald

**Comment by Chekote** [comment]
Low priority. Will not work on today.

**Comment by Chekote** [comment]
I do not think it is wise to make Submodules public, or give FlexibleMink a key so that it can checkout the repo.

If we make it public, we risk exposing sensitive info. At the moment there is at least a list of our private repo's in the non-qa-able-labeler script. There could be more...

If we wanted to give a key to FlexibleMink, we would have to create a new Github user with restricted access, since the standard read/write users we use for services at the moment would give access to ALL private repos.
